import { ThemeProvider } from "@/components/theme-provider";
import { Header } from "@/components/header";
import localFont from "next/font/local";
import type { Metadata } from "next";

import "./globals.css";

const editorialNewUltralightItalic = localFont({
  src: "../fonts/editorial-new-ultralight-italic.ttf",
  variable: "--editorial-new-ultralight-italic",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${editorialNewUltralightItalic.variable} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Header />

          <main>{children}</main>
        </ThemeProvider>
      </body>
    </html>
  );
}
