import { match as matchLocale } from "@formatjs/intl-localematcher";
import { NextRequest, NextResponse } from "next/server";
import { locales, defaultLocale } from "./utils/i18n";
import Negotiator from "negotiator";

function getLocale(request: NextRequest) {
  // First try to get locale from cookie
  const cookieLocale = request.cookies.get('agroloon-locale')?.value;
  if (cookieLocale && locales.includes(cookieLocale as typeof locales[number])) {
    return cookieLocale as typeof locales[number];
  }

  // If no valid cookie, use browser preferences
  const negotiatorHeaders: Record<string, string> = {};
  request.headers.forEach((value, key) => (negotiatorHeaders[key] = value));

  const languages = new Negotiator({ headers: negotiatorHeaders }).languages([
    ...locales,
  ]);

  const locale = matchLocale(languages, locales, defaultLocale);

  return locale;
}

export function middleware(request: NextRequest) {
  const pathname = request.nextUrl.pathname;

  const pathnameHasLocale = locales.some(
    (locale) => pathname.startsWith(`/${locale}/`) || pathname === `/${locale}`
  );

  if (pathnameHasLocale) {
    const locale = pathname.split('/')[1];
    const response = NextResponse.next();
    response.cookies.set('agroloon-locale', locale, {
      path: '/',
      maxAge: 60 * 60 * 24 * 365, // 1 year
    });
    return response;
  }

  const locale = getLocale(request);

  request.nextUrl.pathname = `/${locale}${pathname}`;

  const response = NextResponse.redirect(request.nextUrl);
  response.cookies.set('agroloon-locale', locale, {
    path: '/',
    maxAge: 60 * 60 * 24 * 365, // 1 year
  });
  return response;
}

/** START OF AUTOGENERATED MIDDLEWARE CONFIG */
export const config = {
  matcher: [
    "/((?!api|_next/static|_next/image|favicon.ico|sitemap.xml|robots.txt|agroloon.svg|ascending-drone-first-frame.jpg|ascending-drone-footage.mp4|file.svg|globe.svg|lower-cloud-identification.jpg|lower-cloud-map-clarification.jpg|lower-false-color-analysis.jpg|lower-grvi-vegetation-health.jpg|lower-ndvi-visualization.jpg|lower-nir-road-network.jpg|lower-villages-north-heves.jpg|next.svg|not-found.svg|placeholder.svg|upper-cloud-identification.jpg|upper-cloud-map-clarification.jpg|upper-false-color-analysis.jpg|upper-grvi-vegetation-health.jpg|upper-infrared-water-mapping.jpg|upper-lake-tisza-scenic-view.jpg|upper-ndvi-visualization.jpg|vercel.svg|window.svg).*)"
  ]
};
/** END OF AUTOGENERATED MIDDLEWARE CONFIG */
